- hosts: localhost
  gather_facts: true
  tags: argo
  roles:
  - role: cyverse-ansible.ansible_k8s_argo
  tasks:
  - name: SHELL; deploying mock api for the toolkit
    shell: kubectl apply -f ../api/api.yaml
