apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: nats2
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: nats-dep
      eventSourceName: nats
      eventName: workflow2
  triggers:
    - template:
        name: nats-workflow-trigger2
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: always-false-
              spec:
                entrypoint: always-false
                arguments:
                  parameters:
                  - name: message
                    value: hello world
                  - name: tid
                    value: ""
                templates:
                - name: always-false
                  inputs:
                    parameters:
                    - name: message
                    - name: tid
                  container:
                    image: alpine:latest
                    command: ["false"]
          parameters:
            - src:
                dependencyName: nats-dep
                dataTemplate: "{{ .Input.body.message }}"
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: nats-dep
                dataTemplate: "{{ .Input.body.tid }}"
              dest: spec.arguments.parameters.1.value
