apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api
  strategy: {}
  template:
    metadata:
      labels:
        service: api
    spec:
      containers:
      - name: api
        image: stack0verflow/ccnt-api:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api
  name: api
  namespace: default
spec:
  ports:
  - name: api
    port: 80
    targetPort: 8080
  selector:
    service: api
status:
  loadBalancer: {}
---
# This definition is for /api and keycloak
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ccnt-api-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80